### ISSUE TITLE
Accomodate RAPMM elements in tei_rilm.xsd

### ISSUE THREAD

**Issue by kyarmey** [RILMMusicLit/tei_schema#13] opened 2021-03-12 15:36 UTC
Validation of RAPMM sample files against `tei_rilm.xsd` fails because `<surface>` and its children are not defined there. 
Ken's problem: If I copy `tei_rilm.xsd` to my local machine and try to validate against it, I get errors that I don't get when validating against the schema in `rilm.info/ft/schema/collections`. (1) I don't know why this happens, and (2) in this situation where the existing schema doesn't work, I can't test changes to it unless I keep loading changes to the `ft` site, which I can't do myself. @ahwitz Can you help me in any way, here?

**Comment by ahwitz** [comment] 2021-03-14 18:33
> I can't test changes to it unless I keep loading changes to the ft site, which I can't do myself.

We can get you access pretty easily, but I definitely agree that's not the easiest way.

Can you send me one of the sample files (and, if possible, the errors you're getting) so I can try to reproduce things? Going to try to do it without Oxygen but I may need to get a trial of hat at some point as well.

**Comment by kyarmey** [comment] 2021-03-15 14:39
Here is a small sample file, produced by HTC, and the validation errors.

[rapmm-validation-errors.zip](https://github.com/RILMMusicLit/tei_schema/files/6142121/rapmm-validation-errors.zip)

**Comment by ahwitz** [comment] 2021-03-22 00:37
So with a local copy of tei_rilm.xsd (that was actually a few commits behind), I get the same errors:

![Screen Shot 2021-03-21 at 8 34 01 PM](https://user-images.githubusercontent.com/3514397/111926836-cc219080-8a84-11eb-8a26-15b346b2686f.png)


...and if I add `surface` as a duplicate of `graphic` and to the `mediaLike` definition, I get different errors with my local XSD:

![Screen Shot 2021-03-21 at 8 35 52 PM](https://user-images.githubusercontent.com/3514397/111926902-173ba380-8a85-11eb-9f02-57e55c810586.png)

...so I don't know how to help you. Following questions/screenshots may help:

- Were the errors you sent me the ones from remote or the ones from your machine?
- Can you send me whichever you didn't yet?
- Are you actually doing things through Oxygen still?

If you want to call at some point this coming week, can send me an invite for 3/4PM (or 2 if neither of those work, I _think_ that's safe) on Monday or Tuesday.

**Comment by kyarmey** [comment] 2021-03-22 15:09
Exactly the same thing that happened to me. I'll set up a meeting.

**Comment by ahwitz** [comment] 2021-03-23 21:52
We good to close this now?

**Closed as completed** 2021-03-25 13:10 UTC
